### ISSUE TITLE
Use of angle brackets around file names for include statements

### ISSUE THREAD

**Issue by elfring** [CaptainCrowbar/unicorn-lib#1]
Would you like to [replace any double quotes](https://github.com/CaptainCrowbar/unicorn-lib/blob/cb9cb5dd369d8a4694864e21d32afad62292cfa8/unicorn/file.hpp#L3 "Check header file inclusion style") by [angle brackets around file names for include statements](http://stackoverflow.com/questions/21593/what-is-the-difference-between-include-filename-and-include-filename "What is the difference between #include <filename> and #include “filename”?")?

**Comment by CaptainCrowbar** [comment]
I think this is a matter of personal stylistic preference where there are no widely agreed rules, rather like indentation rules. The C++ standard has no fixed rules on the subject but offers a suggestion: "Although an implementation may provide a mechanism for making arbitrary source files available to the <> search, in general programmers should use the <> form for headers provided with the implementation, and the "" form for sources outside the control of the implementation."

Third party libraries like Unicorn are left in a grey area there, but personally I tend to think they count as "sources outside the control of the implementation" and should usually be included with quotes.

Thee's also the practical matter of compiling the library itself, and its test suite. In that situation, using angles would mean that the compiler will probably find the installed version of the headers instead of the locally modified working copy, which would be a pain for development.

**Comment by elfring** [comment]
I suggest to reconsider the consequences of [the following wording](http://c0x.coding-guidelines.com/6.10.2.html "Source file inclusion") from [the section "16.2 Source file inclusion"](http://open-std.org/jtc1/sc22/wg21/docs/papers/2013/n3797.pdf "C++ working draft") in the standard specification for the programming language "C++".
```
…
The named source file is searched for in an implementation-defined manner. If this search is not supported, or if the search fails, the directive is reprocessed as if it read

#include <h-char-sequence> new-line
…
```

* How do you think about to avoid "a duplicated file search" here?
* Would you like to [restrict the searched directories](https://gcc.gnu.org/onlinedocs/cpp/Include-Syntax.html "Include syntax description") for header files of your software?

**Comment by elfring** [comment]
>Thee's also the practical matter of compiling the library itself, and its test suite. In that situation, using angles would mean that the compiler will probably find the installed version of the headers instead of the locally modified working copy, which would be a pain for development.

How do you think about to handle this concern by a proper configuration for your software build system?
